/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SecurityGuard;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class manageVisitorEntry extends javax.swing.JFrame {

    /**
     * Creates new form manageVisitorEntry
     */
    public manageVisitorEntry() {
        initComponents();
        readVistorEntryTable("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visitorEntry = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EntryName = new javax.swing.JTextField();
        EntryPhoneNumber = new javax.swing.JTextField();
        EntryUnitNumber = new javax.swing.JTextField();
        EntryNumberPlate = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        EntryDate = new com.toedter.calendar.JDateChooser();
        reset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        UpdateEntryDate = new com.toedter.calendar.JDateChooser();
        UpdateEntryName = new javax.swing.JTextField();
        UpdateEntryPhoneNumber = new javax.swing.JTextField();
        UpdateEntryUnitNumber = new javax.swing.JTextField();
        UpdateEntryPlateNumber = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        UpdateVisitorEntryID = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Manage Visitor Entry");

        visitorEntry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }

        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        });
        visitorEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorEntryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(visitorEntry);

        jLabel2.setText("Date : ");

        jLabel3.setText("Name : ");

        jLabel4.setText("Phone Number : ");

        jLabel5.setText("Unit Number : ");

        jLabel6.setText("Number Plate : ");

        EntryPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryPhoneNumberActionPerformed(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(reset)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EntryNumberPlate)
                        .addGap(2, 2, 2))
                    .addComponent(EntryUnitNumber)
                    .addComponent(EntryName)
                    .addComponent(EntryPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(EntryDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(EntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EntryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EntryPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EntryUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EntryNumberPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(reset))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add", jPanel1);

        jLabel7.setText("Date :");

        jLabel8.setText("Name : ");

        jLabel9.setText("Phone Number : ");

        jLabel10.setText("Unit Number : ");

        jLabel11.setText("Number Plate : ");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel12.setText("Visitor Entry ID :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateEntryPhoneNumber)
                            .addComponent(UpdateEntryUnitNumber)
                            .addComponent(UpdateEntryPlateNumber)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateEntryName)
                            .addComponent(UpdateEntryDate, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(UpdateVisitorEntryID))))
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(update)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(UpdateVisitorEntryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(UpdateEntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(UpdateEntryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(UpdateEntryPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(UpdateEntryUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(UpdateEntryPlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(update)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update", jPanel2);

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(back))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void readVistorEntryTable(String query){
        try {
            //read the data from the database
            Map<Integer, Map<String, String>> visitorEntries = new securityGuardFileHandler().getData("visitorEntry", "SecurityGuard");
            //create a table model
            DefaultTableModel model = (DefaultTableModel)visitorEntry.getModel();
            //clear the table
            model.setRowCount(0);
            //set header
            String[] header = {"VISITOR ENTRY ID", "DATE" , "NAME" , "PHONE NUMBER" , "PLATE NUMBER" , "UNIT NUMBER" };
            model.setColumnIdentifiers(header);
            if(query.equals("")){
                for (Map.Entry<Integer, Map<String, String>> entry : visitorEntries.entrySet()) {
                    Map<String, String> visitorEntry = entry.getValue();
                    String[] row = {visitorEntry.get("VISITOR ENTRY ID"), visitorEntry.get("DATE"), visitorEntry.get("NAME"), visitorEntry.get("PHONE NUMBER"), visitorEntry.get("PLATE NUMBER"), visitorEntry.get("UNIT NUMBER")};
                    model.addRow(row);
                }
            }
            else{
                for (Map.Entry<Integer, Map<String, String>> entry : visitorEntries.entrySet()) {
                    Map<String, String> visitorEntry = entry.getValue();
                    if(visitorEntry.get("NAME").equals(query)){
                        String[] row = {visitorEntry.get("VISITOR ENTRY ID"), visitorEntry.get("DATE"), visitorEntry.get("NAME"), visitorEntry.get("PHONE NUMBER"), visitorEntry.get("PLATE NUMBER"), visitorEntry.get("UNIT NUMBER")};
                        model.addRow(row);
                    }
                }
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Date date = EntryDate.getDate();
        String name = EntryName.getText();
        String phoneNumber = EntryPhoneNumber.getText();
        String plateNumber = EntryNumberPlate.getText();
        String unitNumber = EntryUnitNumber.getText();
        if(date == null || name.equals("") || phoneNumber.equals("") || plateNumber.equals("") || unitNumber.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
        }
        else{
            String dateStr = new SimpleDateFormat("dd-MM-yyyy").format(date);
            try {
                new securityGuardFileHandler().addNewEntry(dateStr, name, phoneNumber, plateNumber, unitNumber);
                readVistorEntryTable("");
                //clear the fields
                EntryDate.setDate(null);
                EntryName.setText("");
                EntryPhoneNumber.setText("");
                EntryNumberPlate.setText("");
                EntryUnitNumber.setText("");
                //show success message
                JOptionPane.showMessageDialog(null, "New entry added successfully");
            } catch (Exception e) {
                e.printStackTrace();
            }            
        }

    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String visitorEntryID = UpdateVisitorEntryID.getText();
        Date date = UpdateEntryDate.getDate();
        String name = UpdateEntryName.getText();
        String phoneNumber = UpdateEntryPhoneNumber.getText();
        String plateNumber = UpdateEntryPlateNumber.getText();
        String unitNumber = UpdateEntryUnitNumber.getText();
        if(date == null || name.equals("") || phoneNumber.equals("") || plateNumber.equals("") || unitNumber.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
        }
        else{
            String dateStr = new SimpleDateFormat("dd-MM-yyyy").format(date);
            try {
                HashMap<String, String> entry = new HashMap<>();
                entry.put("VISITOR ENTRY ID", visitorEntryID);  
                entry.put("DATE", dateStr);
                entry.put("NAME", name);
                entry.put("PHONE NUMBER", phoneNumber);
                entry.put("PLATE NUMBER", plateNumber);
                entry.put("UNIT NUMBER", unitNumber);

                boolean isDataUpdated = new securityGuardFileHandler().updateEntryV2(visitorEntryID, entry);

                if (isDataUpdated)
                    readVistorEntryTable("");
                    //clear the fields
                    UpdateEntryDate.setDate(null);
                    UpdateEntryName.setText("");
                    UpdateEntryPhoneNumber.setText("");
                    UpdateEntryPlateNumber.setText("");
                    UpdateEntryUnitNumber.setText("");
                    //show success message
                    JOptionPane.showMessageDialog(null, "Entry updated successfully");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } 
//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        dashboard vp = new dashboard();
        vp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void EntryPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntryPhoneNumberActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        EntryDate.setDate(null);
        EntryName.setText("");
        EntryPhoneNumber.setText("");
        EntryNumberPlate.setText("");
        EntryUnitNumber.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void visitorEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorEntryMouseClicked
        // TODO add your handling code here:
        int selectedRow = visitorEntry.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)visitorEntry.getModel();
        UpdateVisitorEntryID.setText(model.getValueAt (selectedRow, 0).toString());
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String entryDateStr = model.getValueAt (selectedRow, 1).toString();

        Date entryDate = null;

        try {
            entryDate = formatter.parse(entryDateStr);
            } catch (ParseException e) {
                e.printStackTrace();
        }

        UpdateEntryDate.setDate(entryDate);
        UpdateEntryName.setText(model.getValueAt (selectedRow, 2).toString());
        UpdateEntryPhoneNumber.setText(model.getValueAt (selectedRow, 3).toString());
        UpdateEntryUnitNumber.setText(model.getValueAt (selectedRow, 4).toString());
        UpdateEntryPlateNumber.setText(model.getValueAt (selectedRow, 5).toString());

    }//GEN-LAST:event_visitorEntryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageVisitorEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageVisitorEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageVisitorEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageVisitorEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageVisitorEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser EntryDate;
    private javax.swing.JTextField EntryName;
    private javax.swing.JTextField EntryNumberPlate;
    private javax.swing.JTextField EntryPhoneNumber;
    private javax.swing.JTextField EntryUnitNumber;
    private com.toedter.calendar.JDateChooser UpdateEntryDate;
    private javax.swing.JTextField UpdateEntryName;
    private javax.swing.JTextField UpdateEntryPhoneNumber;
    private javax.swing.JTextField UpdateEntryPlateNumber;
    private javax.swing.JTextField UpdateEntryUnitNumber;
    private javax.swing.JTextField UpdateVisitorEntryID;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton reset;
    private javax.swing.JButton update;
    private javax.swing.JTable visitorEntry;
    // End of variables declaration//GEN-END:variables
}
