/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AccountExecutive;

import Helpers.FacilityList;
import User.loginsystem;

import javax.swing.*;

/**
 * @author yudhx
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    public Dashboard(String UID) {
        // Get Customer Information from Login, then initialize
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greetingPanel = new javax.swing.JPanel();
        greetingLabel = new javax.swing.JLabel();
        subgreetingLabel = new javax.swing.JLabel();
        residentPanel = new javax.swing.JPanel();
        residentTitle = new javax.swing.JLabel();
        residentIssueInvoice = new javax.swing.JButton();
        residentIssueReceipt = new javax.swing.JButton();
        residentIssueStatement = new javax.swing.JButton();
        residentRecordPayment = new javax.swing.JButton();
        residentViewPayment = new javax.swing.JButton();
        residentUpdatePayment = new javax.swing.JButton();
        residentViewOutstandingFee = new javax.swing.JButton();
        vendorPanel = new javax.swing.JPanel();
        vendorTitle = new javax.swing.JLabel();
        vendorIssueInvoice = new javax.swing.JButton();
        vendorIssueReceipt = new javax.swing.JButton();
        vendorIssueStatement = new javax.swing.JButton();
        vendorRecordPayment = new javax.swing.JButton();
        vendorViewPayment = new javax.swing.JButton();
        vendorUpdatePayment = new javax.swing.JButton();
        vendorViewOutstandingFee = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        greetingPanel.setBackground(new java.awt.Color(51, 255, 51));
        greetingPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        greetingLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        greetingLabel.setText("Welcome!");

        subgreetingLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        subgreetingLabel.setText("What would you like to do today?");

        javax.swing.GroupLayout greetingPanelLayout = new javax.swing.GroupLayout(greetingPanel);
        greetingPanel.setLayout(greetingPanelLayout);
        greetingPanelLayout.setHorizontalGroup(
                greetingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(greetingPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(greetingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(subgreetingLabel)
                                        .addComponent(greetingLabel))
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        greetingPanelLayout.setVerticalGroup(
                greetingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(greetingPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(greetingLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(subgreetingLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        residentPanel.setBackground(new java.awt.Color(204, 204, 204));
        residentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        residentTitle.setText("Resident");

        residentIssueInvoice.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        residentIssueInvoice.setText("Issue Invoice");
        residentIssueInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentIssueInvoiceActionPerformed(evt);
            }
        });

        residentIssueReceipt.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        residentIssueReceipt.setText("Issue Receipt");
        residentIssueReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentIssueReceiptActionPerformed(evt);
            }
        });

        residentIssueStatement.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        residentIssueStatement.setText("Issue Statement");
        residentIssueStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentIssueStatementActionPerformed(evt);
            }
        });

        residentRecordPayment.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        residentRecordPayment.setText("Record Payment");
        residentRecordPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentRecordPaymentActionPerformed(evt);
            }
        });

        residentViewPayment.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        residentViewPayment.setText("View Payment");
        residentViewPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentViewPaymentActionPerformed(evt);
            }
        });

        residentUpdatePayment.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        residentUpdatePayment.setText("Update Payment");
        residentUpdatePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentUpdatePaymentActionPerformed(evt);
            }
        });

        residentViewOutstandingFee.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        residentViewOutstandingFee.setText("View Outstanding Fee");
        residentViewOutstandingFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentViewOutstandingFeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout residentPanelLayout = new javax.swing.GroupLayout(residentPanel);
        residentPanel.setLayout(residentPanelLayout);
        residentPanelLayout.setHorizontalGroup(
                residentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(residentPanelLayout.createSequentialGroup()
                                .addGroup(residentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(residentPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(residentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(residentIssueInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(residentIssueStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(residentIssueReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(residentRecordPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(residentViewPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(residentUpdatePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(residentViewOutstandingFee)))
                                        .addGroup(residentPanelLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(residentTitle)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        residentPanelLayout.setVerticalGroup(
                residentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(residentPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(residentTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residentIssueInvoice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residentIssueReceipt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residentIssueStatement)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residentRecordPayment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residentViewPayment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residentUpdatePayment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residentViewOutstandingFee)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vendorPanel.setBackground(new java.awt.Color(204, 204, 204));
        vendorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        vendorTitle.setText("Vendor");

        vendorIssueInvoice.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        vendorIssueInvoice.setText("Issue Invoice");
        vendorIssueInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorIssueInvoiceActionPerformed(evt);
            }
        });

        vendorIssueReceipt.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        vendorIssueReceipt.setText("Issue Receipt");
        vendorIssueReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorIssueReceiptActionPerformed(evt);
            }
        });

        vendorIssueStatement.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        vendorIssueStatement.setText("Issue Statement");
        vendorIssueStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorIssueStatementActionPerformed(evt);
            }
        });

        vendorRecordPayment.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        vendorRecordPayment.setText("Record Payment");
        vendorRecordPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorRecordPaymentActionPerformed(evt);
            }
        });

        vendorViewPayment.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        vendorViewPayment.setText("View Payment");
        vendorViewPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorViewPaymentActionPerformed(evt);
            }
        });

        vendorUpdatePayment.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        vendorUpdatePayment.setText("Update Payment");
        vendorUpdatePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorUpdatePaymentActionPerformed(evt);
            }
        });

        vendorViewOutstandingFee.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        vendorViewOutstandingFee.setText("View Outstanding Fee");
        vendorViewOutstandingFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorViewOutstandingFeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vendorPanelLayout = new javax.swing.GroupLayout(vendorPanel);
        vendorPanel.setLayout(vendorPanelLayout);
        vendorPanelLayout.setHorizontalGroup(
                vendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(vendorPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(vendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(vendorIssueInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vendorIssueStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vendorIssueReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vendorRecordPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vendorViewPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vendorUpdatePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vendorViewOutstandingFee))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vendorPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vendorTitle)
                                .addGap(58, 58, 58))
        );
        vendorPanelLayout.setVerticalGroup(
                vendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(vendorPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(vendorTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vendorIssueInvoice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vendorIssueReceipt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vendorIssueStatement)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vendorRecordPayment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vendorViewPayment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vendorUpdatePayment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vendorViewOutstandingFee)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logout.setBackground(new java.awt.Color(255, 51, 51));
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(greetingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(residentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(vendorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(greetingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(residentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(vendorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void residentIssueStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentIssueStatementActionPerformed
        // close this current window and bring up the issue statement window
        issueStatement issueStatement = new issueStatement("Resident");
        issueStatement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_residentIssueStatementActionPerformed

    private void residentIssueReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentIssueReceiptActionPerformed
        // close this current window and bring up the issue receipt window
        issueReceipt issueReceipt = new issueReceipt("Resident");
        issueReceipt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_residentIssueReceiptActionPerformed

    private void residentIssueInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentIssueInvoiceActionPerformed
        //close this current window and bring up the issue invoice window
        issueInvoice issueInvoice = new issueInvoice("Resident");
        issueInvoice.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_residentIssueInvoiceActionPerformed

    private void residentRecordPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentRecordPaymentActionPerformed
        //close this current window and bring up the record payment window
        recordPayment recordPayment = new recordPayment("Resident");
        recordPayment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_residentRecordPaymentActionPerformed

    private void residentViewPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentViewPaymentActionPerformed
        //close this current window and bring up the view payment window
        viewPayment viewPayment = new viewPayment("Resident");
        viewPayment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_residentViewPaymentActionPerformed

    private void residentUpdatePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentUpdatePaymentActionPerformed
        //close this current window and bring up the update payment window
        updatePayment updatePayment = new updatePayment("Resident");
        updatePayment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_residentUpdatePaymentActionPerformed

    private void residentViewOutstandingFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentViewOutstandingFeeActionPerformed
        // close this current window and bring up the view outstanding fee window
        viewOutstandingFee viewOutstandingFee = new viewOutstandingFee("Resident");
        viewOutstandingFee.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_residentViewOutstandingFeeActionPerformed

    private void vendorIssueInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorIssueInvoiceActionPerformed
        //close this current window and bring up the issue invoice window
        issueInvoice issueInvoice = new issueInvoice("Vendor");
        issueInvoice.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vendorIssueInvoiceActionPerformed

    private void vendorIssueReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorIssueReceiptActionPerformed
        //close this current window and bring up the issue receipt window
        issueReceipt issueReceipt = new issueReceipt("Vendor");
        issueReceipt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vendorIssueReceiptActionPerformed

    private void vendorIssueStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorIssueStatementActionPerformed
        //close this current window and bring up the issue statement window
        issueStatement issueStatement = new issueStatement("Vendor");
        issueStatement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vendorIssueStatementActionPerformed

    private void vendorRecordPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorRecordPaymentActionPerformed
        // //close this window and bring up the record payment window
        recordPayment recordPayment = new recordPayment("Vendor");
        recordPayment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vendorRecordPaymentActionPerformed

    private void vendorViewPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorViewPaymentActionPerformed
        // close this window and bring up the view payment window
        viewPayment viewPayment = new viewPayment("Vendor");
        viewPayment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vendorViewPaymentActionPerformed

    private void vendorUpdatePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorUpdatePaymentActionPerformed
        // close this window and bring up the update payment window
        updatePayment updatePayment = new updatePayment("Vendor");
        updatePayment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vendorUpdatePaymentActionPerformed

    private void vendorViewOutstandingFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorViewOutstandingFeeActionPerformed
        // close this window and bring up the view outstanding fee window
        viewOutstandingFee viewOutstandingFee = new viewOutstandingFee("Vendor");
        viewOutstandingFee.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vendorViewOutstandingFeeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // first prompt the user if they are sure they want to logout, if yes, then close the current window and bring up the login window
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", dialogButton);
        if (dialogResult == 0) {
            User.loginsystem loginsystem = new loginsystem();
            loginsystem.setVisible(true);
            this.dispose();
            //exit the program
        }

    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JPanel greetingPanel;
    private javax.swing.JButton logout;
    private javax.swing.JButton residentIssueInvoice;
    private javax.swing.JButton residentIssueReceipt;
    private javax.swing.JButton residentIssueStatement;
    private javax.swing.JPanel residentPanel;
    private javax.swing.JButton residentRecordPayment;
    private javax.swing.JLabel residentTitle;
    private javax.swing.JButton residentUpdatePayment;
    private javax.swing.JButton residentViewOutstandingFee;
    private javax.swing.JButton residentViewPayment;
    private javax.swing.JLabel subgreetingLabel;
    private javax.swing.JButton vendorIssueInvoice;
    private javax.swing.JButton vendorIssueReceipt;
    private javax.swing.JButton vendorIssueStatement;
    private javax.swing.JPanel vendorPanel;
    private javax.swing.JButton vendorRecordPayment;
    private javax.swing.JLabel vendorTitle;
    private javax.swing.JButton vendorUpdatePayment;
    private javax.swing.JButton vendorViewOutstandingFee;
    private javax.swing.JButton vendorViewPayment;
    // End of variables declaration//GEN-END:variables
}
