package Helpers;

public enum AccountExecutiveFiles {
    residentInvoice(new String[]{"RESIDENT INVOICE DETAILS", "THIS FILE STORES DETAILS TO CREATE AN INVOICE FOR RESIDENT",
            "RESIDENT NAME", "RESIDENT ID", "INVOICE DATE", "AMOUNT", "INVOICE NUMBER"}),
    residentPayment(new String[]{"RESIDENT PAYMENT DETAILS", "THIS FILE STORES PAYMENT DETAILS FOR RESIDENTS",
            "DATE", "RESIDENT ID", "AMOUNT", "AMOUNT PAID", "TOTAL AMOUNT DUE", "RECEIPT ID"}),
    residentReceipt(new String[]{"RESIDENT RECEIPT DETAILS", "THIS FILE STORES DETAILS TO CREATE A RECEIPT FOR RESIDENTS",
            "DATE", "RECEIPT ID", "RESIDENT ID", "INVOICE ID", "STATEMENT ID", "AMOUNT", "TOTAL AMOUNT PAID"}),
    residentStatement(new String[]{"RESIDENT STATEMENT DETAILS", "THIS FILE STORES DETAILS TO CREATE A STATEMENT FOR RESIDENTS",
            "DATE", "RESIDENT NAME", "RESIDENT ID", "BUILDING", "UNIT NUMBER", "DESCRIPTION", "AMOUNT", "TOTAL AMOUNT DUE", "STATEMENT ID"}),
    vendorInvoice(new String[]{"VENDOR INVOICE DETAILS", "THIS FILE STORES DETAILS TO CREATE AN INVOICE FOR VENDORS",
            "VENDOR NAME", "VENDOR ID", "INVOICE DATE", "AMOUNT", "INVOICE NUMBER"}),
    vendorPayment(new String[]{"VENDOR PAYMENT DETAILS", "THIS FILE STORES PAYMENT DETAILS FOR VENDORS",
            "DATE", "VENDOR ID", "AMOUNT", "AMOUNT PAID", "TOTAL AMOUNT DUE", "RECEIPT ID"}),
    vendorReceipt(new String[]{"VENDOR RECEIPT DETAILS", "THIS FILE STORES DETAILS TO CREATE A RECEIPT FOR VENDORS",
            "DATE", "RECEIPT ID", "VENDOR ID", "INVOICE ID", "STATEMENT ID", "AMOUNT", "TOTAL AMOUNT PAID"}),
    vendorStatement(new String[]{"VENDOR STATEMENT DETAILS", "THIS FILE STORES DETAILS TO CREATE A STATEMENT FOR VENDORS",
            "DATE", "VENDOR NAME", "VENDOR ID", "BUILDING", "UNIT NUMBER", "DESCRIPTION", "AMOUNT", "TOTAL AMOUNT DUE", "STATEMENT ID"});
    private final String[] headers;

    private AccountExecutiveFiles(String[] headers) {
        this.headers = headers;
    }

    public String[] getHeaders() {
        return headers;
    }
}

